{
	"version": 1633631342,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bush-sheet0.png",
		"images/grass-sheet0.png",
		"images/treetall-sheet0.png",
		"images/rock-sheet0.png",
		"images/rock-sheet1.png",
		"images/rock-sheet2.png",
		"images/raindrop-sheet0.png",
		"images/bowerring-sheet0.png",
		"images/bowerbase-sheet0.png",
		"images/bowerornamate-sheet0.png",
		"images/bowerclick-sheet0.png",
		"images/inventoryitem-sheet0.png",
		"images/collisionbase-sheet0.png",
		"images/heart-sheet0.png",
		"images/win-sheet0.png",
		"images/winfadein-sheet0.png",
		"images/bower-sheet0.png",
		"images/bower-sheet1.png",
		"images/bower-sheet2.png",
		"images/item-sheet0.png",
		"images/camera-sheet0.png",
		"images/girlbower-sheet0.png",
		"images/girlbower-sheet1.png",
		"media/picking up an item.ogg",
		"media/bird flying.ogg",
		"media/forest-sounds-woodland-ambience-bird-song-nearby-village-3-hours.ogg",
		"media/bird noises 1.ogg",
		"media/bird noises 2.ogg",
		"media/bird noises 3.ogg",
		"media/whipping winds.ogg",
		"media/soft rain.ogg",
		"media/cat noise.ogg",
		"media/people walk in the forest.ogg",
		"media/the owl family.ogg",
		"media/wolf_coyote noise.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}