{
	"version": 1633590217,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bush-sheet0.png",
		"images/grass-sheet0.png",
		"images/treetall-sheet0.png",
		"images/bowerring-sheet0.png",
		"images/bowerbase-sheet0.png",
		"images/bowerornamate-sheet0.png",
		"images/bowerclick-sheet0.png",
		"images/inventoryitem-sheet0.png",
		"images/collisionbase-sheet0.png",
		"images/heart-sheet0.png",
		"images/bower-sheet0.png",
		"images/bower-sheet1.png",
		"images/bower-sheet2.png",
		"images/item-sheet0.png",
		"images/camera-sheet0.png",
		"images/girlbower-sheet0.png",
		"images/girlbower-sheet1.png",
		"media/picking up an item.ogg",
		"media/bird flying.ogg",
		"media/forest-sounds-woodland-ambience-bird-song-nearby-village-3-hours.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}